logging:
  level:
    com.github.bkhablenko: debug
    web: debug

spring:
  application:
    name: pizza-toppings

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:app}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari:
      connection-timeout: 15000
      leak-detection-threshold: 10000
      maximum-pool-size: 15

  # Disable the warning (JpaBaseConfiguration$JpaWebConfiguration)
  # https://www.baeldung.com/spring-open-session-in-view
  jpa:
    open-in-view: false
